"""
RSA Race Model Fitting

Fits the race model to Experiment 1 data (2x2 design: time pressure × frequency ratio).

Model: A(w, t) = B(w) + δ · M(θ, w) · t

Parameters:
  - Shared across conditions: σ (semantic width), δ (drift rate), λ (lapse)
  - Varies by frequency ratio: B_HF (baseline advantage for HF words)
  - Varies by condition: T (effective processing time)

Usage:
    From repository root:  python models/fit.py
    From models/ directory (data path still uses repo root):  python fit.py

Data:
    Expects data/full-production/processed_data/production.csv and participants.csv
    (generated by analysis/cogsci2026/00_clean_data.R from raw_data/run-1).
    Next-nearest angle is reconstructed from geometry (nearest ±45°; whichever is closer to target),
    not from the jsPsych/CSV next_nearest_angle column.

Output:
    - race_model_data_exp1.csv: Trial-level data used for fit (for R so plots use same data as Python)
    - Fitted parameters and fit statistics printed to console
    - race_model_fit.png: Model fit visualization
    - fitted_params.npz, fitted_params_exp1.csv: Saved parameters
    - race_model_predictions_exp1.csv, race_model_schematic_data.csv, race_model_schematic_params.csv
    - race_model_P_LF_P_HF_vs_time_exp1_LF_prototype.csv (and optional .png/.pdf)
"""

import pandas as pd
import numpy as np
from scipy.optimize import minimize
from scipy.stats import chi2, norm as scipy_norm
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import jax
import jax.numpy as jnp
from rsa_race import race_model

# Vectorized race model for batch computation
_race_model_vec = jax.vmap(race_model, in_axes=(0, None, 0, None, 0, None))


# =============================================================================
# Data Loading
# =============================================================================

def _circ_dist(a, b):
    """Circular distance in [0, 360)."""
    d = np.abs(a - b)
    return np.minimum(d, 360 - d)


def _next_nearest_angle_from_geometry(nearest_deg, target_deg):
    """
    Next-nearest trained angle = the closer of the two ±45° neighbors of nearest (mod 360).
    Reconstruct from geometry; do not use jsPsych/CSV next_nearest_angle.
    """
    nearest = np.asarray(nearest_deg, dtype=float)
    target = np.asarray(target_deg, dtype=float)
    n_plus = (nearest + 45) % 360
    n_minus = (nearest - 45 + 360) % 360
    d_plus = _circ_dist(target, n_plus)
    d_minus = _circ_dist(target, n_minus)
    return np.where(d_plus < d_minus, n_plus, n_minus)


def load_data():
    """Load and preprocess Experiment 1 data."""
    data_dir = Path(__file__).parent.parent / "data" / "full-production" / "processed_data"

    production = pd.read_csv(data_dir / "production.csv")
    participants = pd.read_csv(data_dir / "participants.csv")

    df = production.merge(
        participants[["subject_id", "time_pressure", "frequency_ratio"]],
        on="subject_id"
    )
    df["time_pressure"] = pd.to_numeric(df["time_pressure"], errors="coerce")
    df = df.dropna(subset=["time_pressure"])

    # Reconstruct next-nearest from geometry (nearest ±45°; whichever is closer to target). Do not use CSV column.
    df["nextNearestAngle"] = _next_nearest_angle_from_geometry(
        df["nearestAngle"].values, df["targetAngle"].values
    )

    # Compute distance to nearest LF trained angle
    df["dist_to_lf_deg"] = np.where(
        df["nearestFreq"] == "LF",
        np.abs(df["distance"]),
        _circ_dist(df["targetAngle"].values, df["nextNearestAngle"].values)
    )

    # Convert to model's theta space (0.5 = LF prototype, 0/1 = HF prototypes)
    df["theta"] = 0.5 - df["dist_to_lf_deg"] / 90

    # Filter to critical trials
    df = df[df["between_freqs"]]              # Between-frequency trials only
    df = df[df["timed_out"] == 0]              # Exclude timeouts
    df = df[(df["rt"] > 200) &                 # Exclude very fast responses
            (df["rt"] < df["time_pressure"] * 1000)]  # Exclude responses after deadline

    df["is_lf"] = (df["responseFreq"] == "LF").astype(int)

    return df


# =============================================================================
# Loss Functions
# =============================================================================

def neg_log_likelihood(params, df):
    """Full model (8 params, delta fixed to 1)."""
    sigma, B_hf_12, B_hf_14, lapse, T_12_5, T_12_10, T_14_5, T_14_10 = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if any(t <= 0 for t in [T_12_5, T_12_10, T_14_5, T_14_10]):
        return 1e10
    tp = df["time_pressure"].values
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    T = np.where((tp == 5) & fr_is_12, T_12_5,
            np.where((tp == 10) & fr_is_12, T_12_10,
                np.where(tp == 5, T_14_5, T_14_10)))
    B_hf = np.where(fr_is_12, B_hf_12, B_hf_14)
    return _compute_nll_vec(df["theta"].values, T, B_hf, df["is_lf"].values, sigma, lapse)


# =============================================================================
# Fitting
# =============================================================================

def fit_model(df):
    """Fit Interaction model (delta fixed to 1)."""
    x0 = [0.2, 0.5, 0.9, 0.15, 2.0, 3.5, 1.0]

    print(f"Fitting Interaction model ({len(df):,} trials)...")
    result = minimize(nll_interaction, x0, args=(df,), method='Nelder-Mead',
                      options={'maxiter': 2000, 'xatol': 1e-4, 'fatol': 1e-4})

    param_names = ["sigma", "B_hf_12", "B_hf_14", "lapse", "T_5", "T_10", "gamma"]
    params = {name: val for name, val in zip(param_names, result.x)}

    params["T_12_5"] = params["T_5"]
    params["T_12_10"] = params["T_10"]
    params["T_14_5"] = params["T_5"] + params["gamma"]
    params["T_14_10"] = params["T_10"]

    params["nll"] = result.fun
    params["n_trials"] = len(df)

    return params


# =============================================================================
# Model Comparison
# =============================================================================

def _compute_nll_vec(theta, T, B_hf, y, sigma, lapse):
    """Vectorized NLL computation (delta fixed to 1)."""
    try:
        probs = _race_model_vec(
            jnp.array(theta), sigma, jnp.array(B_hf), 1.0, jnp.array(T), lapse)
        p_lf = np.array(probs[:, 1])
    except Exception:
        return 1e10

    eps = 1e-10
    p_lf = np.clip(p_lf, eps, 1 - eps)
    return -np.sum(y * np.log(p_lf) + (1 - y) * np.log(1 - p_lf))


def nll_shared_B(params, df):
    """Shared B_HF across frequency ratios (7 params)."""
    sigma, B_hf, lapse, T_12_5, T_12_10, T_14_5, T_14_10 = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if any(t <= 0 for t in [T_12_5, T_12_10, T_14_5, T_14_10]):
        return 1e10
    tp = df["time_pressure"].values
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    T = np.where((tp == 5) & fr_is_12, T_12_5,
            np.where((tp == 10) & fr_is_12, T_12_10,
                np.where(tp == 5, T_14_5, T_14_10)))
    return _compute_nll_vec(df["theta"].values, T, np.full(len(df), B_hf), df["is_lf"].values, sigma, lapse)


def nll_shared_T(params, df):
    """Shared T across frequency ratios (6 params)."""
    sigma, B_hf_12, B_hf_14, lapse, T_5, T_10 = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if T_5 <= 0 or T_10 <= 0:
        return 1e10
    tp = df["time_pressure"].values
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    T = np.where(tp == 5, T_5, T_10)
    B = np.where(fr_is_12, B_hf_12, B_hf_14)
    return _compute_nll_vec(df["theta"].values, T, B, df["is_lf"].values, sigma, lapse)


def nll_minimal(params, df):
    """Minimal: shared B_HF and shared T (5 params)."""
    sigma, B_hf, lapse, T_5, T_10 = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if T_5 <= 0 or T_10 <= 0:
        return 1e10
    tp = df["time_pressure"].values
    T = np.where(tp == 5, T_5, T_10)
    return _compute_nll_vec(df["theta"].values, T, np.full(len(df), B_hf), df["is_lf"].values, sigma, lapse)


def nll_interaction(params, df):
    """Interaction model (7 params, delta fixed to 1)."""
    sigma, B_hf_12, B_hf_14, lapse, T_5, T_10, gamma = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if T_5 <= 0 or T_10 <= 0:
        return 1e10
    tp = df["time_pressure"].values
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    T = np.where(tp == 5, T_5, T_10) + np.where((tp == 5) & ~fr_is_12, gamma, 0)
    B = np.where(fr_is_12, B_hf_12, B_hf_14)
    return _compute_nll_vec(df["theta"].values, T, B, df["is_lf"].values, sigma, lapse)


def nll_shared_B_interaction(params, df):
    """Shared B_HF with T interaction (6 params, delta fixed to 1)."""
    sigma, B_hf, lapse, T_5, T_10, gamma = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if T_5 <= 0 or T_10 <= 0:
        return 1e10
    tp = df["time_pressure"].values
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    T = np.where(tp == 5, T_5, T_10) + np.where((tp == 5) & ~fr_is_12, gamma, 0)
    return _compute_nll_vec(df["theta"].values, T, np.full(len(df), B_hf), df["is_lf"].values, sigma, lapse)


def nll_no_TP_effect(params, df):
    """B_HF varies by FR, but T is shared across time pressure (5 params)."""
    sigma, B_hf_12, B_hf_14, lapse, T = params
    if sigma <= 0.05 or sigma > 2.0 or lapse < 0 or lapse > 0.5:
        return 1e10
    if T <= 0:
        return 1e10
    fr_is_12 = (df["frequency_ratio"] == "1:2").values
    B = np.where(fr_is_12, B_hf_12, B_hf_14)
    return _compute_nll_vec(df["theta"].values, np.full(len(df), T), B, df["is_lf"].values, sigma, lapse)


def fit_model_comparison(df, full_params=None):
    """Fit all model variants and compare using AIC/BIC. Delta fixed to 1."""
    n_obs = len(df)
    models = {}

    # Base starting values: sigma, B_12, B_14, lapse, T_12_5, T_12_10, T_14_5, T_14_10
    if full_params is None:
        x0 = [0.2, 0.5, 0.9, 0.15, 2.0, 3.5, 3.0, 3.5]
    else:
        x0 = [full_params["sigma"], full_params["B_hf_12"], full_params["B_hf_14"],
              full_params["lapse"], full_params["T_12_5"], full_params["T_12_10"],
              full_params["T_14_5"], full_params["T_14_10"]]

    def fit_variant(name, nll_fn, x0, bounds, k):
        print(f"  {name}...", end=" ", flush=True)
        result = minimize(nll_fn, x0, args=(df,), method='L-BFGS-B', bounds=bounds)
        print(f"NLL={result.fun:.1f}")
        return {"k": k, "nll": result.fun}

    # Bounds for each model variant
    b_sig = (0.1, 2.0)
    b_B = (-2.0, 2.0)
    b_lapse = (0.01, 0.3)
    b_T = (0.1, 30.0)
    b_gamma = (-10.0, 10.0)

    models["Full (B×FR, T×FR×TP)"] = fit_variant("Full (8)", neg_log_likelihood,
        x0, [b_sig, b_B, b_B, b_lapse, b_T, b_T, b_T, b_T], 8)
    models["Shared B_HF (T×FR×TP)"] = fit_variant("Shared B (7)", nll_shared_B,
        [x0[0], (x0[1]+x0[2])/2, x0[3], x0[4], x0[5], x0[6], x0[7]],
        [b_sig, b_B, b_lapse, b_T, b_T, b_T, b_T], 7)
    models["Shared T (B×FR, T×TP)"] = fit_variant("Shared T (6)", nll_shared_T,
        [x0[0], x0[1], x0[2], x0[3], (x0[4]+x0[6])/2, (x0[5]+x0[7])/2],
        [b_sig, b_B, b_B, b_lapse, b_T, b_T], 6)
    models["Minimal (shared B, T×TP)"] = fit_variant("Minimal (5)", nll_minimal,
        [x0[0], (x0[1]+x0[2])/2, x0[3], (x0[4]+x0[6])/2, (x0[5]+x0[7])/2],
        [b_sig, b_B, b_lapse, b_T, b_T], 5)
    models["Interaction (B×FR, T+γ)"] = fit_variant("Interaction (7)", nll_interaction,
        [x0[0], x0[1], x0[2], x0[3], x0[4], x0[5], x0[6] - x0[4]],
        [b_sig, b_B, b_B, b_lapse, b_T, b_T, b_gamma], 7)
    models["Shared B + Interaction (T+γ)"] = fit_variant("Shared B + Int (6)", nll_shared_B_interaction,
        [x0[0], (x0[1]+x0[2])/2, x0[3], x0[4], x0[5], x0[6] - x0[4]],
        [b_sig, b_B, b_lapse, b_T, b_T, b_gamma], 6)
    models["No TP effect (B×FR, T shared)"] = fit_variant("No TP effect (5)", nll_no_TP_effect,
        [x0[0], x0[1], x0[2], x0[3], (x0[4]+x0[5]+x0[6]+x0[7])/4],
        [b_sig, b_B, b_B, b_lapse, b_T], 5)

    for m in models.values():
        m["aic"] = 2 * m["k"] + 2 * m["nll"]
        m["bic"] = m["k"] * np.log(n_obs) + 2 * m["nll"]

    return models, n_obs


# =============================================================================
# Visualization: raw data + model fit overlay
# =============================================================================

def plot_fit(df, params, out_dir=None):
    """
    Plot P(LF) vs distance from LF: binned raw data + fitted race model curves.

    Two panels (frequency ratio 1:2 and 1:4); within each, two curves (5s vs 10s).
    Saves race_model_fit.png and race_model_fit.pdf to out_dir (default: models/).
    """
    if out_dir is None:
        out_dir = Path(__file__).parent
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    n_bins = 9
    dist_lo, dist_hi = 0.0, 45.0
    dist_grid = np.linspace(0.5, 44.5, 200)

    # Binned raw data: mean and SE of is_lf by condition and distance bin
    df_plot = df.copy()
    df_plot["dist_bin"] = pd.cut(
        df_plot["dist_to_lf_deg"],
        bins=np.linspace(dist_lo, dist_hi, n_bins + 1),
        include_lowest=True,
    )
    binned = (
        df_plot.groupby(["frequency_ratio", "time_pressure", "dist_bin"], observed=True)
        .agg(
            dist_mean=("dist_to_lf_deg", "mean"),
            p_lf=("is_lf", "mean"),
            n=("is_lf", "count"),
        )
        .reset_index()
    )
    binned["p_lf_se"] = np.sqrt(binned["p_lf"] * (1 - binned["p_lf"]) / binned["n"])

    # Model curves: P(LF) on fine grid for each of 4 conditions (δ fixed to 1)
    sigma = params["sigma"]
    lapse = params["lapse"]
    theta_grid = 0.5 - dist_grid / 90.0

    def curve_p_lf(B_hf, T):
        probs = _race_model_vec(
            jnp.array(theta_grid),
            sigma,
            jnp.full(len(theta_grid), B_hf),
            1.0,
            jnp.full(len(theta_grid), T),
            lapse,
        )
        return np.array(probs[:, 1])

    curves = {}
    T_by_cond = {
        ("1:2", 5): "T_12_5", ("1:2", 10): "T_12_10",
        ("1:4", 5): "T_14_5", ("1:4", 10): "T_14_10",
    }
    for fr, B_hf in [("1:2", params["B_hf_12"]), ("1:4", params["B_hf_14"])]:
        for tp in [5, 10]:
            T_val = params[T_by_cond[(fr, tp)]]
            curves[(fr, tp)] = curve_p_lf(B_hf, T_val)

    # Colors to match paper (strict 5s = red, lenient 10s = blue)
    colors_tp = {5: "#E94F37", 10: "#2E86AB"}

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5), sharey=True)
    for ax, fr in zip(axes, ["1:2", "1:4"]):
        for tp in [5, 10]:
            sub = binned[(binned["frequency_ratio"] == fr) & (binned["time_pressure"] == tp)]
            ax.errorbar(
                sub["dist_mean"],
                sub["p_lf"],
                yerr=sub["p_lf_se"],
                fmt="o",
                color=colors_tp[tp],
                capsize=3,
                label=f"{'Strict (5s)' if tp == 5 else 'Lenient (10s)'}",
            )
            ax.plot(
                dist_grid,
                curves[(fr, tp)],
                color=colors_tp[tp],
                linewidth=1.5,
            )
        ax.axvline(22.5, color="gray", linestyle="--", linewidth=1)
        ax.set_xlim(0, 45)
        ax.set_ylim(0, 1)
        ax.set_xlabel("Distance from LF (deg)")
        ax.set_ylabel("P(LF)" if ax == axes[0] else "")
        ax.set_title(f"Frequency ratio {fr}")
        ax.legend(loc="upper right", framealpha=0.9)
        ax.set_xticks(np.arange(0, 46, 10))
        ax.set_yticks(np.arange(0, 1.25, 0.25))
        ax.grid(True, alpha=0.3)
    plt.tight_layout()

    for ext in ["png", "pdf"]:
        out_path = out_dir / f"race_model_fit.{ext}"
        fig.savefig(out_path, bbox_inches="tight", dpi=300 if ext == "png" else None)
        print(f"Saved {out_path}")
    plt.close(fig)

    # Export prediction grid for R/ggplot (tidy: dist_to_lf, frequency_ratio, time_pressure, p_lf)
    pred_rows = []
    for fr in ["1:2", "1:4"]:
        for tp in [5, 10]:
            p_lf = curves[(fr, tp)]
            for d, p in zip(dist_grid, p_lf):
                pred_rows.append({"dist_to_lf": d, "frequency_ratio": fr, "time_pressure": tp, "p_lf": p})
    pd.DataFrame(pred_rows).to_csv(out_dir / "race_model_predictions_exp1.csv", index=False)
    print(f"Saved {out_dir / 'race_model_predictions_exp1.csv'}")


# =============================================================================
# Schematic: activation vs time (baselines + slopes) for paper
# =============================================================================

def plot_race_schematic(params, out_dir=None, theta=0.5, suffix=""):
    """
    Plot activation vs time at a given θ: HF vs LF baseline at t=0 and slopes (δ·M(θ,w)).
    Uses fitted σ, B_HF; δ=1. Saves race_model_schematic[suffix].png/pdf and CSVs for R/ggplot.

    theta: 0.5 = LF prototype (LF slope >> HF slope); 0.25 = boundary (LF slope = HF slope).
    suffix: e.g. "_boundary" for boundary figure filename.
    """
    if out_dir is None:
        out_dir = Path(__file__).parent
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sigma = params["sigma"]
    delta = 1.0
    word_locs = [0.0, 0.5, 1.0]  # HF1, LF, HF2
    # At boundary (θ=0.25), nearest HF is at 0: M(0.25,0) = M(0.25,0.5) by symmetry
    M_hf = float(scipy_norm.pdf(theta, word_locs[0], sigma))
    M_lf = float(scipy_norm.pdf(theta, word_locs[1], sigma))
    slope_hf = delta * M_hf
    slope_lf = delta * M_lf

    t_max = 6.0
    t_vals = np.linspace(0, t_max, 200)

    # Colors to match paper
    color_hf = "#7B7B7B"
    color_lf = "#2E86AB"
    color_t5 = "#E94F37"
    color_t10 = "#2E86AB"

    fig, axes = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
    for ax, (fr, B_hf, T_5, T_10) in zip(
        axes,
        [
            ("1:2", params["B_hf_12"], params["T_12_5"], params["T_12_10"]),
            ("1:4", params["B_hf_14"], params["T_14_5"], params["T_14_10"]),
        ],
    ):
        # A(HF, t) = B_HF + slope_hf * t; A(LF, t) = 0 + slope_lf * t
        A_hf = B_hf + slope_hf * t_vals
        A_lf = 0 + slope_lf * t_vals
        ax.plot(t_vals, A_hf, color=color_hf, lw=2, label=f"HF (B = {B_hf:.2f})")
        ax.plot(t_vals, A_lf, color=color_lf, lw=2, label=f"LF (B = 0)")
        ax.axhline(B_hf, color=color_hf, ls=":", alpha=0.6)
        ax.axhline(0, color=color_lf, ls=":", alpha=0.6)
        ax.axvline(T_5, color=color_t5, ls="--", lw=1.5, alpha=0.8)
        ax.axvline(T_10, color=color_t10, ls="--", lw=1.5, alpha=0.8)
        ax.set_xlim(0, t_max)
        ax.set_xlabel("Time (effective units)")
        ax.set_ylabel("Activation" if ax == axes[0] else "")
        ax.set_title(f"Frequency ratio {fr}")
        ax.legend(loc="upper left", frameon=True, fontsize=8)
        ax.grid(True, alpha=0.3)
        # Annotate slopes and position
        theta_label = "θ = 0.5 (LF prototype)" if theta == 0.5 else "θ = 0.25 (boundary)"
        ax.text(0.98, 0.02, f"{theta_label}\nslope HF = {slope_hf:.3f}\nslope LF = {slope_lf:.3f}",
                transform=ax.transAxes, fontsize=7, va="bottom", ha="right",
                bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5))
    plt.tight_layout()

    base = f"race_model_schematic{suffix}"
    for ext in ["png", "pdf"]:
        out_path = out_dir / f"{base}.{ext}"
        fig.savefig(out_path, bbox_inches="tight", dpi=300 if ext == "png" else None)
        print(f"Saved {out_path}")
    plt.close(fig)

    # Export schematic data for R/ggplot (only for default prototype run to avoid overwriting)
    if suffix == "":
        schematic_data = []
        for fr, B_hf in [("1:2", params["B_hf_12"]), ("1:4", params["B_hf_14"])]:
            for word, baseline, slope in [
                ("HF", B_hf, slope_hf),
                ("LF", 0.0, slope_lf),
            ]:
                for t in np.linspace(0, t_max, 50):
                    schematic_data.append({
                        "frequency_ratio": fr,
                        "word": word,
                        "baseline": baseline,
                        "slope": slope,
                        "t": t,
                        "activation": baseline + slope * t,
                    })
        pd.DataFrame(schematic_data).to_csv(out_dir / "race_model_schematic_data.csv", index=False)
        summary = []
        for fr, B_hf in [("1:2", params["B_hf_12"]), ("1:4", params["B_hf_14"])]:
            summary.append({"frequency_ratio": fr, "word": "HF", "baseline": B_hf, "slope": slope_hf})
            summary.append({"frequency_ratio": fr, "word": "LF", "baseline": 0.0, "slope": slope_lf})
        pd.DataFrame(summary).to_csv(out_dir / "race_model_schematic_params.csv", index=False)
        print(f"Saved {out_dir / 'race_model_schematic_data.csv'} and race_model_schematic_params.csv")


# =============================================================================
# P(LF) and P(HF) as a function of decision time (T)
# =============================================================================

def plot_P_LF_P_HF_vs_time_exp1(params, out_dir=None, theta=0.5, theta_label=None, suffix=""):
    """
    Plot P(LF) and P(HF) on the same axes as a function of effective decision time T.

    Shows how producers shift from HF to LF (or vice versa) as T increases.
    Uses fitted σ, B_HF per FR; at a fixed θ. Two panels (FR 1:2, FR 1:4).
    Exports CSV for R/ggplot (experiment1_race_model.qmd plot #3).

    At θ=0.5 (LF prototype), M(θ, LF) is maximal and LF can beat HF as T increases.
    """
    if out_dir is None:
        out_dir = Path(__file__).parent
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if theta_label is None:
        theta_label = f"θ = {theta}" + (" (LF prototype)" if theta == 0.5 else " (boundary)" if theta == 0.25 else "")

    sigma = params["sigma"]
    lapse = params["lapse"]
    T_grid = np.linspace(0, 5.0, 300)
    theta_vec = jnp.full(len(T_grid), theta)

    color_lf = "#2980B9"
    color_hf = "#7B7B7B"
    color_t5 = "#D4A017"
    color_t10 = "#9C27B0"

    fig, axes = plt.subplots(1, 2, figsize=(10, 5), sharex=True, sharey=True)

    for i_col, fr in enumerate(["1:2", "1:4"]):
        ax = axes[i_col]
        B_hf = params["B_hf_12"] if fr == "1:2" else params["B_hf_14"]
        probs = _race_model_vec(
            theta_vec,
            sigma,
            jnp.full(len(T_grid), B_hf),
            1.0,
            jnp.array(T_grid),
            lapse,
        )
        probs = np.array(probs)
        p_lf = probs[:, 1]
        p_hf = probs[:, 0] + probs[:, 2]

        ax.plot(T_grid, p_lf, color=color_lf, linewidth=1.5, label="P(LF)")
        ax.plot(T_grid, p_hf, color=color_hf, linewidth=1.5, label="P(HF)")

        T_5 = params["T_12_5"] if fr == "1:2" else params["T_14_5"]
        T_10 = params["T_12_10"] if fr == "1:2" else params["T_14_10"]
        if T_5 <= T_grid.max():
            idx5 = np.argmin(np.abs(T_grid - T_5))
            ax.axvline(T_5, color=color_t5, ls="--", lw=1.2, alpha=0.8, label="Strict (5s)")
            ax.plot(T_5, p_lf[idx5], "o", color=color_lf, markersize=6)
            ax.plot(T_5, p_hf[idx5], "o", color=color_hf, markersize=6)
        if T_10 <= T_grid.max():
            idx10 = np.argmin(np.abs(T_grid - T_10))
            ax.axvline(T_10, color=color_t10, ls="--", lw=1.2, alpha=0.8, label="Lenient (10s)")
            ax.plot(T_10, p_lf[idx10], "o", color=color_lf, markersize=6)
            ax.plot(T_10, p_hf[idx10], "o", color=color_hf, markersize=6)

        ax.set_xlim(T_grid.min(), T_grid.max())
        ax.set_ylim(0, 1)
        ax.set_xlabel("Effective decision time T")
        ax.set_ylabel("P(LF) / P(HF)" if i_col == 0 else "")
        ax.set_title(f"FR {fr}")
        ax.legend(loc="center right", frameon=True, fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.text(0.02, 0.98, theta_label, transform=ax.transAxes, fontsize=7, va="top", ha="left")

    plt.tight_layout()
    base = f"race_model_P_LF_P_HF_vs_time_exp1{suffix}"
    for ext in ["png", "pdf"]:
        out_path = out_dir / f"{base}.{ext}"
        fig.savefig(out_path, bbox_inches="tight", dpi=300 if ext == "png" else None)
        print(f"Saved {out_path}")
    plt.close(fig)

    # Export curve grid for R/ggplot: T, p_lf, p_hf per frequency_ratio (no payoff_structure in exp1)
    curve_rows = []
    for fr in ["1:2", "1:4"]:
        B_hf = params["B_hf_12"] if fr == "1:2" else params["B_hf_14"]
        probs = _race_model_vec(
            theta_vec,
            sigma,
            jnp.full(len(T_grid), B_hf),
            1.0,
            jnp.array(T_grid),
            lapse,
        )
        probs = np.array(probs)
        p_lf = probs[:, 1]
        p_hf = probs[:, 0] + probs[:, 2]
        for t, plf, phf in zip(T_grid, p_lf, p_hf):
            curve_rows.append({
                "frequency_ratio": fr, "T": t, "p_lf": plf, "p_hf": phf, "theta": theta,
            })
    out_csv = out_dir / f"race_model_P_LF_P_HF_vs_time_exp1{suffix}.csv"
    pd.DataFrame(curve_rows).to_csv(out_csv, index=False)
    print(f"Saved {out_csv}")


# =============================================================================
# Main
# =============================================================================

def main():
    print("=" * 70)
    print("RSA RACE MODEL FITTING (Trial-level NLL)")
    print("=" * 70)
    print()

    # Load data
    print("Loading data...")
    df = load_data()
    print(f"  N = {len(df):,} trials from {df['subject_id'].nunique()} participants")
    print()

    # Export trial-level data used for fitting (so R can plot same data and align with model)
    out_dir = Path(__file__).parent
    df_export = df[["dist_to_lf_deg", "is_lf", "time_pressure", "frequency_ratio"]].copy()
    df_export = df_export.rename(columns={"dist_to_lf_deg": "dist_to_lf", "is_lf": "responded_lf"})
    df_export.to_csv(out_dir / "race_model_data_exp1.csv", index=False)
    print("Saved race_model_data_exp1.csv (trial-level data used for fit)")
    print()

    # Show condition breakdown
    for tp in [5, 10]:
        for fr in ["1:2", "1:4"]:
            n = len(df[(df["time_pressure"] == tp) & (df["frequency_ratio"] == fr)])
            print(f"  Condition T={tp}s, FR={fr}: {n:,} trials")
    print()

    print("-" * 70)
    params = fit_model(df)
    print()

    # Print results
    print("=" * 70)
    print("FITTED PARAMETERS")
    print("=" * 70)
    print()
    print("Shared across conditions (δ fixed to 1):")
    print(f"  σ (semantic width) = {params['sigma']:.3f}")
    print(f"  λ (lapse rate)     = {params['lapse']:.3f}")
    print()
    print("By frequency ratio:")
    print(f"  B_HF (1:2) = {params['B_hf_12']:.3f}")
    print(f"  B_HF (1:4) = {params['B_hf_14']:.3f}")
    print(f"  Δ B_HF     = {params['B_hf_14'] - params['B_hf_12']:.3f} (1:4 - 1:2)")
    print()
    print("Interaction model parameters:")
    print(f"  T_5 (base at 5s)  = {params['T_5']:.2f}")
    print(f"  T_10 (base at 10s) = {params['T_10']:.2f}")
    print(f"  γ (1:4 offset at 5s) = {params['gamma']:.2f}")
    print()
    print("Derived T values:")
    print(f"  1:2, 5s:  T = T_5 = {params['T_12_5']:.2f}")
    print(f"  1:2, 10s: T = T_10 = {params['T_12_10']:.2f}")
    print(f"  1:4, 5s:  T = T_5 + γ = {params['T_14_5']:.2f}")
    print(f"  1:4, 10s: T = T_10 = {params['T_14_10']:.2f}")
    print()

    print("Time pressure effect (ΔT = T_10 - T_5):")
    delta_T_12 = params['T_10'] - params['T_5']
    delta_T_14 = params['T_10'] - (params['T_5'] + params['gamma'])
    print(f"  1:2: ΔT = {delta_T_12:.2f}")
    print(f"  1:4: ΔT = {delta_T_14:.2f}")
    print(f"  Ratio: {delta_T_12 / delta_T_14:.2f}x")
    print()

    # Save parameters
    out_dir = Path(__file__).parent
    save_params = {k: v for k, v in params.items() if k not in ["nll", "n_trials"]}
    np.savez(out_dir / "fitted_params.npz", **save_params)
    pd.DataFrame([save_params]).to_csv(out_dir / "fitted_params_exp1.csv", index=False)
    print("Saved fitted_params.npz and fitted_params_exp1.csv")
    print()

    # Overlay figure: raw data + model curves
    print("Plotting fit overlay...")
    plot_fit(df, params, out_dir=out_dir)
    print()

    # Schematic: activation vs time (baselines + slopes)
    print("Plotting race model schematic (θ = 0.5, LF prototype)...")
    plot_race_schematic(params, out_dir=out_dir, theta=0.5)
    print("Plotting race model schematic (θ = 0.25, boundary)...")
    plot_race_schematic(params, out_dir=out_dir, theta=0.25, suffix="_boundary")
    print()

    # P(LF) and P(HF) vs decision time (for experiment1_race_model.qmd plot #3)
    print("Plotting P(LF) and P(HF) vs decision time (LF prototype)...")
    plot_P_LF_P_HF_vs_time_exp1(params, out_dir=out_dir, theta=0.5, suffix="_LF_prototype")
    print()

    # Model comparison
    print("=" * 70)
    print("MODEL COMPARISON")
    print("=" * 70)
    print()
    print("Fitting model variants...")
    model_variants, n_obs = fit_model_comparison(df, full_params=params)
    print()

    # Sort by AIC
    sorted_models = sorted(model_variants.items(), key=lambda x: x[1]["aic"])

    print(f"{'Model':<30} {'k':>3} {'NLL':>12} {'AIC':>12} {'BIC':>12} {'ΔAIC':>8}")
    print("-" * 80)
    best_aic = sorted_models[0][1]["aic"]
    for name, m in sorted_models:
        delta_aic = m["aic"] - best_aic
        print(f"{name:<30} {m['k']:>3} {m['nll']:>12.1f} {m['aic']:>12.1f} {m['bic']:>12.1f} {delta_aic:>8.1f}")
    print()
    print(f"N trials: {n_obs:,}")
    print()

    # Likelihood ratio tests for nested models
    print("Likelihood Ratio Tests (against Interaction model):")
    print("-" * 60)

    nll_int = model_variants["Interaction (B×FR, T+γ)"]["nll"]
    nll_shared_t = model_variants["Shared T (B×FR, T×TP)"]["nll"]
    nll_shared_b_int = model_variants["Shared B + Interaction (T+γ)"]["nll"]
    nll_no_tp = model_variants["No TP effect (B×FR, T shared)"]["nll"]

    # Test B_HF variation: Interaction vs Shared B + Interaction
    lr = 2 * (nll_shared_b_int - nll_int)
    print(f"  Effect of B_HF × FR:       LR = {lr:.2f}, df = 1, p = {1 - chi2.cdf(lr, 1):.3f}")
    print(f"    (Interaction vs Shared B + Interaction)")

    # Test T main effect of time pressure: Interaction vs No TP effect
    lr = 2 * (nll_no_tp - nll_int)
    print(f"  Effect of T × TP:          LR = {lr:.2f}, df = 2, p = {1 - chi2.cdf(lr, 2):.3f}")
    print(f"    (Interaction vs No TP effect)")

    # Test T interaction: Interaction vs Shared T
    lr = 2 * (nll_shared_t - nll_int)
    print(f"  Effect of T × FR (γ):      LR = {lr:.2f}, df = 1, p = {1 - chi2.cdf(lr, 1):.3f}")
    print(f"    (Interaction vs Shared T)")
    print()

    return params


if __name__ == "__main__":
    params = main()
